#!/usr/bin/env python
# -*- coding:utf-8 -*-

RELATIVE_USER_CONFIG = {
    54 : 2,
}

SUPER_ADMIN_UID = 1
SUPER_ADMIN_USER_LIST = {
    1:-1,
    2:8,
}

MASSIVAL_INNER_USER_PERMISSION = [2,3,4,8]

MASSIVAL_MD_USER_LIST = [62, 63, 64, 65, 67, 68, 69, 70]
RELATIVE_EVENT_USER_CONFIG = {
    1 : MASSIVAL_MD_USER_LIST,
    2 : MASSIVAL_MD_USER_LIST,
    57 : MASSIVAL_MD_USER_LIST,
}

