BROWSER_LIST = [
	("All", "All"),
	("Chrome Mobile", "Chrome Mobile"),
	("Android Webkit", "Android Webkit"),
	("Chromium", "Chromium"),
	("UCWeb", "UCWeb"),
	("Opera Mini", "Opera Mini"),
	("Firefox Mobile", "Firefox Mobile"),
	("IEMobile", "IEMobile"),
	("Safari", "Safari"),
	("MSIE", "MSIE"),
	("Fennec", "Fennec"),
	("Firefox Desktop", "Firefox Desktop"),
	("Opera Mobi", "Opera Mobi"),
	("Opera Tablet", "Opera Tablet"),
	("Opera", "Opera"),
	("BlackBerry", "BlackBerry"),
	("Nokia BrowserNG", "Nokia BrowserNG"),
	("Nokia", "Nokia"),
	("MQQ Browser", "MQQ Browser"),
	("LGUPlus WebKit", "LGUPlus WebKit"),
	("Gecko/Minimo", "Gecko/Minimo"),
	("Nokia Proxy Browser", "Nokia Proxy Browser"),
	("Access Netfront", "Access Netfront"),
	("Openwave Mobile Browser", "Openwave Mobile Browser"),
	("Microsoft Mobile Explorer", "Microsoft Mobile Explorer"),
	("Teleca-Obigo", "Teleca-Obigo"),
	("Presto/Opera Mini", "Presto/Opera Mini"),
	("Dolfin/Jasmine Webkit", "Dolfin/Jasmine Webkit"),
	("MAUI Wap Browser", "MAUI Wap Browser"),
]
