#!/usr/bin/env python
# -*- coding:utf-8 -*-


COUNTRY_NAME_LIST_ORI = [
    ["Global", "GLOBAL", 0],
    ["Afghanistan", "AF", 1],
    ["Aland Islands", "AX", 1],
    ["Albania", "AL", 1],
    ["Algeria", "DZ", 1],
    ["American Samoa", "AS", 1],
    ["Andorra", "AD", 1],
    ["Angola", "AO", 1],
    ["Anguilla", "AI", 1],
    ["Antigua and Barbuda", "AG", 1],
    ["Argentina", "AR", 1],
    ["Armenia", "AM", 1],
    ["Aruba", "AW", 1],
    ["Australia", "AU", 1],
    ["Austria", "AT", 1],
    ["Azerbaijan", "AZ", 1],
    ["Bangladesh", "BD", 1],
    ["Bahrain", "BH", 1],
    ["Bahamas", "BS", 1],
    ["Barbados", "BB", 1],
    ["Belarus", "BY", 1],
    ["Belgium", "BE", 1],
    ["Belize", "BZ", 1],
    ["Benin", "BJ", 1],
    ["Bermuda", "BM", 1],
    ["Bhutan", "BT", 1],
    ["Bolivia", "BO", 1],
    ["Bosnia and Herzegovina", "BA", 1],
    ["Botswana", "BW", 1],
    ["Bouvet Island", "BV", 1],
    ["Brazil", "BR", 1],
    ["Brunei", "BN", 1],
    ["Bulgaria", "BG", 1],
    ["Burkina Faso", "BF", 1],
    ["Burundi", "BI", 1],
    ["Cambodia", "KH", 1],
    ["Cameroon", "CM", 1],
    ["Canada", "CA", 1],
    ["Cape Verde", "CV", 1],
    ["Central African Republic", "CF", 1],
    ["Chad", "TD", 1],
    ["Chile", "CL", 1],
    ["Christmas Islands", "CX", 1],
    ["Cocos (keeling) Islands", "CC", 1],
    ["Colombia", "CO", 1],
    ["Comoros", "KM", 1],
    ["Congo (Congo-Kinshasa)", "CD", 1],
    ["Congo", "CG", 1],
    ["Cook Islands", "CK", 1],
    ["Costa Rica", "CR", 1],
    ["Cote D'Ivoire", "CI", 1],
    ["China", "CN", 1],
    ["Croatia", "HR", 1],
    ["Cuba", "CU", 1],
    ["Czech", "CZ", 1],
    ["Cyprus", "CY", 1],
    ["Denmark", "DK", 1],
    ["Djibouti", "DJ", 1],
    ["Dominica", "DM", 1],
    ["East Timor", "　　", 1],
    ["Ecuador", "EC", 1],
    ["Egypt", "EG", 1],
    ["Equatorial Guinea", "GQ", 1],
    ["Eritrea", "ER", 1],
    ["Estonia", "EE", 1],
    ["Ethiopia", "ET", 1],
    ["Faroe Islands", "FO", 1],
    ["Fiji", "FJ", 1],
    ["Finland", "FI", 1],
    ["France", "FR", 1],
    ["Franch Metropolitan", "FX", 1],
    ["Franch Guiana", "GF", 1],
    ["French Polynesia", "PF", 1],
    ["Gabon", "GA", 1],
    ["Gambia", "GM", 1],
    ["Georgia", "GE", 1],
    ["Germany", "DE", 1],
    ["Ghana", "GH", 1],
    ["Gibraltar", "GI", 1],
    ["Greece", "GR", 1],
    ["Grenada", "GD", 1],
    ["Guadeloupe", "GP", 1],
    ["Guam", "GU", 1],
    ["Guatemala", "GT", 1],
    ["Guernsey", "GG", 1],
    ["Guinea-Bissau", "GW", 1],
    ["Guinea", "GN", 1],
    ["Guyana", "GY", 1],
    ["Hong Kong", "HK", 1],
    ["Haiti", "HT", 1],
    ["Honduras", "HN", 1],
    ["Hungary", "HU", 1],
    ["Iceland", "IS", 1],
    ["India", "IN", 1],
    ["Indonesia", "ID", 1],
    ["Iran", "IR", 1],
    ["Iraq", "IQ", 1],
    ["Ireland", "IE", 1],
    ["Isle of Man", "IM", 1],
    ["Israel", "IL", 1],
    ["Italy", "IT", 1],
    ["Jamaica", "JM", 1],
    ["Japan", "JP", 1],
    ["Jersey", "JE", 1],
    ["Jordan", "JO", 1],
    ["Kazakstan", "KZ", 1],
    ["Kenya", "KE", 1],
    ["Kiribati", "KI", 1],
    ["Korea (South)", "KR", 1],
    ["Korea (North)", "KD", 1],
    ["Kuwait", "KW", 1],
    ["Kyrgyzstan", "KG", 1],
    ["Laos", "LO", 1],
    ["Latvia", "LV", 1],
    ["Lebanon", "LB", 1],
    ["Lesotho", "LS", 1],
    ["Liberia", "LR", 1],
    ["Libya", "LY", 1],
    ["Liechtenstein", "LI", 1],
    ["Lithuania", "LT", 1],
    ["Luxembourg", "LU", 1],
    ["Macau", "MO", 1],
    ["Macedonia", "MK", 1],
    ["Malawi", "MW", 1],
    ["Malaysia", "MY", 1],
    ["Madagascar", "MG", 1],
    ["Maldives", "MV", 1],
    ["Mali", "ML", 1],
    ["Malta", "MT", 1],
    ["Marshall Islands", "MH", 1],
    ["Martinique", "MQ", 1],
    ["Mauritania", "MR", 1],
    ["Mauritius", "MU", 1],
    ["Mayotte", "YT", 1],
    ["Mexico", "MX", 1],
    ["Micronesia", "MF", 1],
    ["Moldova", "MD", 1],
    ["Monaco", "MC", 1],
    ["Mongolia", "MN", 1],
    ["Montenegro", "ME", 1],
    ["Montserrat", "MS", 1],
    ["Morocco", "MA", 1],
    ["Mozambique", "MZ", 1],
    ["Myanmar", "MM", 1],
    ["Namibia", "NA", 1],
    ["Nauru", "NR", 1],
    ["Nepal", "NP", 1],
    ["Netherlands", "NL", 1],
    ["New Caledonia", "NC", 1],
    ["New Zealand", "NZ", 1],
    ["Nicaragua", "NI", 1],
    ["Niger", "NE", 1],
    ["Nigeria", "NG", 1],
    ["Niue", "NU", 1],
    ["Norfolk Island", "NF", 1],
    ["Norway", "NO", 1],
    ["Oman", "OM", 1],
    ["Pakistan", "PK", 1],
    ["Palau", "PW", 1],
    ["Palestine", "PS", 1],
    ["Panama", "PA", 1],
    ["Papua New Guinea", "PG", 1],
    ["Paraguay", "PY", 1],
    ["Peru", "PE", 1],
    ["Philippines", "PH", 1],
    ["Pitcairn Islands", "PN", 1],
    ["Poland", "PL", 1],
    ["Portugal", "PT", 1],
    ["Puerto Rico", "PR", 1],
    ["Qatar", "QA", 1],
    ["Reunion", "RE", 1],
    ["Romania", "RO", 1],
    ["Rwanda", "RW", 1],
    ["Russian Federation", "RU", 1],
    ["Saint Helena", "SH", 1],
    ["Saint Kitts-Nevis", "KN", 1],
    ["Saint Lucia", "LC", 1],
    ["Saint Vincent and the Grenadines", "VG", 1],
    ["El Salvador", "SV", 1],
    ["Samoa", "WS", 1],
    ["San Marino", "SM", 1],
    ["Sao Tome and Principe", "ST", 1],
    ["Saudi Arabia", "SA", 1],
    ["Senegal", "SN", 1],
    ["Seychelles", "SC", 1],
    ["Sierra Leone", "SL", 1],
    ["Singapore", "SG", 1],
    ["Serbia", "RS", 1],
    ["Slovakia", "SK", 1],
    ["Slovenia", "SI", 1],
    ["Solomon Islands", "SB", 1],
    ["Somalia", "SO", 1],
    ["South Africa", "ZA", 1],
    ["Spain", "ES", 1],
    ["Sri Lanka", "LK", 1],
    ["Sudan", "SD", 1],
    ["Suriname", "SR", 1],
    ["Swaziland", "SZ", 1],
    ["Sweden", "SE", 1],
    ["Switzerland", "CH", 1],
    ["Syria", "SY", 1],
    ["Tajikistan", "TJ", 1],
    ["Tanzania", "TZ", 1],
    ["Taiwan", "TW", 1],
    ["Thailand", "TH", 1],
    ["Trinidad and Tobago", "TT", 1],
    ["Timor-Leste", "TL", 1],
    ["Togo", "TG", 1],
    ["Tokelau", "TK", 1],
    ["Tonga", "TO", 1],
    ["Tunisia", "TN", 1],
    ["Turkey", "TR", 1],
    ["Turkmenistan", "TM", 1],
    ["Tuvalu", "TV", 1],
    ["Uganda", "UG", 1],
    ["Ukraine", "UA", 1],
    ["United Arab Emirates", "AE", 1],
    ["United Kingdom", "UK", 1],
    ["United States", "US", 1],
    ["Uruguay", "UY", 1],
    ["Uzbekistan", "UZ", 1],
    ["Vanuatu", "VU", 1],
    ["Vatican City", "VA", 1],
    ["Venezuela", "VE", 1],
    ["Vietnam", "VN", 1],
    ["Wallis and Futuna", "WF", 1],
    ["Western Sahara", "EH", 1],
    ["Yemen", "YE", 1],
    ["Yugoslavia", "YU", 1],
    ["Zambia", "ZM", 1],
    ["Zimbabwe", "ZW", 1],
]

COUNTRY_NAME_LIST = []

if not COUNTRY_NAME_LIST:
    for name, val, v in COUNTRY_NAME_LIST_ORI:
        if name != "Global":
            n = "%s-%s" % (val, name)
        else:
            n = name
        tmp = [n, val, v]
        COUNTRY_NAME_LIST.append(tmp)

country_name_map = {}

if not country_name_map:
    for name, val, _ in COUNTRY_NAME_LIST_ORI:
        country_name_map[val] = "(%s)%s" % (val, name)

if __name__ == "__main__":
    print len(COUNTRY_NAME_LIST)
    c = [n for n, _ in COUNTRY_NAME_LIST]
    print len(set(c))
