#!/usr/bin/env python
# -*- coding:utf-8 -*-

PERMISSION_IGNORE = -1
PERMISSION_CONFIGURE = 0
PERMISSION_REPORT = 1
PERMISSION_APIOFFER = 2
PERMISSION_TOOLS = 3
PERMISSION_DASHBOARD = 4

PERMISSION_DASHBOARD_SHOW = 1

PERMISSION_CONFIGURE_CUSTOM_OFFER = 32
PERMISSION_CONFIGURE_ADMIN_TRAFFIC_SOURCE = 1024
PERMISSION_CONFIGURE_MASSIVAL_OFFER = 16
PERMISSION_CONFIGURE_CAMPAIGN = 128
PERMISSION_CONFIGURE_DOMIAN_INFO = 1
PERMISSION_CONFIGURE_SWITCH_PATH = 4096
PERMISSION_CONFIGURE_LANDPAGE = 64
PERMISSION_CONFIGURE_TRAFFIC_SOURCE = 2
PERMISSION_CONFIGURE_DIRECT_OFFER = 8
PERMISSION_CONFIGURE_MAIL = 256
PERMISSION_CONFIGURE_ADMIN_AFFILIATE_NETWORK = 2048
PERMISSION_CONFIGURE_ADMIN_OFFER = 512
PERMISSION_CONFIGURE_NETWORK = 4

PERMISSION_REPORT_ZERO_ENCRYPT = 16
PERMISSION_REPORT_NORMAL = 1
PERMISSION_REPORT_ENCRYPT = 4
PERMISSION_REPORT_ADMIN = 2
PERMISSION_REPORT_ZERO = 8

PERMISSION_API_OFFER_IRONSOURCE = 2
PERMISSION_API_OFFER_MOBVISTA = 1

PERMISSION_TOOLS_EVENTS = 1
PERMISSION_TOOLS_RELATIVE_EVENTS = 2
PERMISSION_TOOLS_DECRYPT = 4

PERMISSION_CONFIGURE_ALL_OFFER = 56

PERMISSION_REPORT_ALL = 11
